import cv2
import numpy as np
from PIL import ImageGrab
import ctypes

# --- Globals for mouse callback, needs to be reset for each run ---
ref_point = []
cropping = False

def _select_area(event, x, y, flags, param):
    """Internal mouse callback function to select a rectangle."""
    global ref_point, cropping
    image_clone = param
    if event == cv2.EVENT_LBUTTONDOWN:
        ref_point = [(x, y)]
        cropping = True
    elif event == cv2.EVENT_LBUTTONUP:
        ref_point.append((x, y))
        cropping = False
        cv2.rectangle(image_clone, ref_point[0], ref_point[1], (0, 255, 0), 2)
        cv2.imshow("미니맵 설정 (c: 확정, r: 초기화, q: 취소)", image_clone)

def run_minimap_configuration():
    """
    Captures the entire screen, allows the user to select the minimap area,
    saves the absolute screen coordinates, and returns them.

    Returns:
        dict: new_coords if successful, otherwise None.
    """
    # Fix for screen scaling (DPI) issue on Windows
    try:
        ctypes.windll.shcore.SetProcessDpiAwareness(1)
    except AttributeError:
        # This is for Windows versions older than 8.1
        try:
            ctypes.windll.user32.SetProcessDPIAware()
        except AttributeError:
            pass # Not on Windows or very old version
    except Exception as e:
        print(f"경고: DPI 인식을 설정할 수 없습니다. {e}")

    global ref_point, cropping
    ref_point = []
    cropping = False

    print("전체 화면을 캡처합니다...")
    try:
        screenshot = ImageGrab.grab(all_screens=True)
        image = cv2.cvtColor(np.array(screenshot), cv2.COLOR_RGB2BGR)
    except Exception as e:
        print(f"오류: 화면을 캡처할 수 없습니다: {e}")
        return None

    clone = image.copy()
    window_name = "미니맵 설정 (c: 확정, r: 초기화, q: 취소)"
    cv2.namedWindow(window_name, cv2.WND_PROP_FULLSCREEN)
    cv2.setWindowProperty(window_name, cv2.WND_PROP_FULLSCREEN, cv2.WINDOW_FULLSCREEN)
    cv2.setMouseCallback(window_name, _select_area, clone)

    print("전체 화면에서 미니맵 영역을 마우스로 드래그하여 선택하세요.")
    print("'c' 키를 눌러 확정, 'r' 키로 다시 선택, 'q' 키로 취소합니다.")

    while True:
        cv2.imshow(window_name, clone)
        key = cv2.waitKey(1) & 0xFF

        if key == ord("r"):
            clone = image.copy()
            print("선택이 초기화되었습니다. 다시 선택하세요.")
        elif key == ord("c"):
            if len(ref_point) == 2:
                break
            else:
                print("영역이 선택되지 않았습니다.")
        elif key == ord("q"):
            cv2.destroyAllWindows()
            print("미니맵 설정을 취소했습니다.")
            return None
    
    cv2.destroyAllWindows()

    top_left = (min(ref_point[0][0], ref_point[1][0]), min(ref_point[0][1], ref_point[1][1]))
    bottom_right = (max(ref_point[0][0], ref_point[1][0]), max(ref_point[0][1], ref_point[1][1]))

    new_coords = {
        "x": top_left[0],
        "y": top_left[1],
        "width": bottom_right[0] - top_left[0],
        "height": bottom_right[1] - top_left[1]
    }

    # Remove the unreliable game window title
    config_content = f'# This file is automatically generated.\n\nMINIMAP_COORDS = {new_coords}\n'

    try:
        with open("minimap_config.py", "w", encoding="utf-8") as f:
            f.write(config_content)
        print("미니맵 영역 설정 완료. 절대 좌표가 저장되었습니다.")
        print(f"좌표: {new_coords}")
        return new_coords
    except IOError as e:
        print(f"오류: 설정 파일을 저장할 수 없습니다: {e}")
        return None
